version: '3.8'
services:
  db-charity:
    container_name: charity-mysql-db
    image: 'mysql:8'
    env_file: .env
    volumes:
      - ./dbdata:/var/lib/mysql
    environment:
          - MYSQL_USER=roott
#          - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
          - MYSQL_RANDOM_ROOT_PASSWORD==$MYSQLDB_ROOT_PASSWORD
          - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
          - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    restart: always
  app-charity:
    image: charity-app
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    volumes:
      - /data/charity-app
#    depends_on:
#      db-charity:
#        condition: service_healthy
##version: "3.8"
##
##services:
##  charity-mysqldb:
##    image: charity-db
##    restart: unless-stopped
##    env_file: .env
##    environment:
##      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
##      - MYSQL_DATABASE=$MYSQLDB_DATABASE
##    ports:
##      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
##    volumes:
##      - db:/var/lib/mysql
##  charity-app:
##    depends_on:
##      - charity-mysqldb
##    build: /
##    restart: on-failure
##    env_file: .env
##    ports:
##      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
##    environment:
##      SPRING_APPLICATION_JSON: '{
##        "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
##        "spring.datasource.username" : "$MYSQLDB_USER",
##        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
##        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
##        "spring.jpa.hibernate.ddl-auto" : "update"
##      }'
##    volumes:
##      - .m2:/root/.m2
##    stdin_open: true
##    tty: true
##
##volumes:
##  db:
#version: '3.8'
#services:
#  database:
#    container_name: charity-mysql-db
#    restart: always
#    image: mysql-db
#    ports:
#      - 3306:3306
#    environment:
#      MYSQL_ROOT_PASSWORD: example
#  java:
#    image: charity-app
#    links:
#      - "database"