version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build: ./
    restart: on-failure
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?serverTimezone=UTC",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
#    volumes:
#    - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db:

#version: '3'
#
#services:
#
#  mysql-charity:
#    image: mysql:8.0
#    environment:
#      - MYSQL_ROOT_PASSWORD=root
#      - MYSQL_DATABASE=charity-db
#      - MYSQL_USER=root
#      - MYSQL_PASSWORD=Borys19041986
#    ports:
#      - 3306:3306
#
#  app-charity:
#    image: charity-app
#    restart: on-failure
#    depends_on:
#      - mysql-charity
#    ports:
#      - 8080:8080
#    environment:
#      - DATABASE_HOST=mysql-charity
#      - DATABASE_USER=root
#      - DATABASE_PASSWORD=Borys19041986
#      - DATABASE_NAME=charity-db
#      - DATABASE_PORT=3306